quarkus.http.port=8086
quarkus.http.root-path=/api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=db_user
quarkus.datasource.password=204753
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gps_db
%docker.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-db:5432/gps_db

quarkus.hibernate-orm.database.generation=none
quarkus.log.category."io.smallrye.faulttolerance".level=DEBUG

# Kafka - consumer
mp.messaging.incoming.gps-events.connector=smallrye-kafka
mp.messaging.incoming.gps-events.topic=gps-tracking
mp.messaging.incoming.gps-events.bootstrap.servers=localhost:9092
%docker.mp.messaging.incoming.gps-events.bootstrap.servers=kafka:29092
mp.messaging.incoming.gps-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.gps-events.value.deserializer.value.type=com.gps.alert.kafka.GpsEvent
