quarkus.http.port=8081
quarkus.http.root-path=/api
quarkus.smallrye-health.root-path=/health
quarkus.http.cors=true
quarkus.http.cors.origins=*

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=db_user
quarkus.datasource.password=204753
quarkus.datasource.jdbc.url=jdbc:mysql://mysql-db:3306/customer_db

quarkus.hibernate-orm.database=mysql
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.database.generation=none
