quarkus.http.port=8083
quarkus.http.root-path=/api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=db_user
quarkus.datasource.password=204753
quarkus.datasource.reactive.url=postgresql://localhost:5432/gps_db
%docker.quarkus.datasource.reactive.url=postgresql://postgres-db:5432/gps_db

quarkus.hibernate-orm.database.generation=none