quarkus.http.port=8083
quarkus.http.root-path=/api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=db_user
quarkus.datasource.password=204753
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-db:5432/gps_db

quarkus.hibernate-orm.database.generation=none
