quarkus.http.port=8080
quarkus.http.root-path=/api
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.rest-client.jackson.enabled=true
quarkus.smallrye-health.root-path=/health
quarkus.smallrye-health.enabled=true
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger-ui
# =========================
# REST Client URLs
# =========================
# User MS
user-api/mp-rest/url=http://user-ms:8080
# User MS Backup
backup-api/mp-rest/url=http://backup-ms:8080
# Device MS
device-api/mp-rest/url=http://device-ms:8080
# Vehicle MS
vehicle-api/mp-rest/url=http://vehicle-ms:8080
# Tracking MS
tracking-api/mp-rest/url=http://tracking-ms:8080
# Alert MS
alert-api/mp-rest/url=http://alert-ms:8080