apiVersion: v1
kind: Service
metadata:
  namespace: jsw-gps
  name: vehicle-service
spec:
  type: NodePort
  selector:
    app: vehicle
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30081