quarkus.http.port=8085
quarkus.http.root-path=/api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gps_db
%docker.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-db:5432/gps_db
quarkus.datasource.username=db_user
quarkus.datasource.password=204753

quarkus.hibernate-orm.database.generation=none
quarkus.log.category."io.smallrye.faulttolerance".level=DEBUG

quarkus.cache.caffeine.devices.expire-after-write=30S
quarkus.cache.caffeine.devices.maximum-size=10000
quarkus.cache.caffeine.vehicles.expire-after-write=30S
quarkus.cache.caffeine.vehicles.maximum-size=10000

# Device MS
quarkus.rest-client.device-ms.url=http://localhost:8083
%docker.quarkus.rest-client.device-ms.url=http://device-ms:8080
quarkus.rest-client.device-ms.connect-timeout=3000
quarkus.rest-client.device-ms.read-timeout=5000

# Vehicle MS
quarkus.rest-client.vehicle-ms.url=http://localhost:8084
%docker.quarkus.rest-client.vehicle-ms.url=http://vehicle-ms:8080
quarkus.rest-client.vehicle-ms.connect-timeout=3000
quarkus.rest-client.vehicle-ms.read-timeout=5000

# User MS
quarkus.rest-client.user-ms.url=http://localhost:8081
%docker.quarkus.rest-client.user-ms.url=http://user-ms:8080
quarkus.rest-client.user-ms.connect-timeout=3000
quarkus.rest-client.user-ms.read-timeout=5000