quarkus.http.port=8085
quarkus.http.root-path=/api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=db_user
quarkus.datasource.password=204753
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gps_db
%docker.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-db:5432/gps_db

quarkus.hibernate-orm.database.generation=none
quarkus.log.category."io.smallrye.faulttolerance".level=DEBUG

# Kafka
mp.messaging.outgoing.gps-events.connector=smallrye-kafka
mp.messaging.outgoing.gps-events.topic=gps-tracking
mp.messaging.outgoing.gps-events.bootstrap.servers=localhost:9092
%docker.mp.messaging.outgoing.gps-events.bootstrap.servers=kafka:29092
mp.messaging.outgoing.gps-events.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Caching
quarkus.cache.caffeine.devices.expire-after-write=30S
quarkus.cache.caffeine.devices.maximum-size=10000
quarkus.cache.caffeine.vehicles.expire-after-write=30S
quarkus.cache.caffeine.vehicles.maximum-size=10000

# Device MS
quarkus.rest-client.device-ms.url=http://localhost:8083
%docker.quarkus.rest-client.device-ms.url=http://device-ms:8080

# Vehicle MS
quarkus.rest-client.vehicle-ms.url=http://localhost:8084
%docker.quarkus.rest-client.vehicle-ms.url=http://vehicle-ms:8080

# User MS
quarkus.rest-client.user-ms.url=http://localhost:8081
%docker.quarkus.rest-client.user-ms.url=http://user-ms:8080