quarkus.http.port=8084
quarkus.http.root-path=/api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:db_user}
quarkus.datasource.password=${DB_PSW:204753}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://postgres-db:5432/gps_db}

quarkus.hibernate-orm.database.generation=none
